### ISSUE TITLE
TODO 김동석

### ISSUE THREAD

**Issue by bluedskim** [SEONGNAM-SELLDOK/CLONE-PROJECT#39]
## 지원현황
- [x] 엔티티 생성, 기존 엔티티들에 릴레이션 추가 
  - [x] 생성 API_12/13
  - [x] 수정 API(지원현황 상태변경)
  - [x] 상태값 갯수(ex. 진행중 : 5, 종료: 1, 합격 : 1)
  - [x] 리스트 API(지원회사 검색 가능, 동적 검색 샘플)
- [ ] 화면개발 작성(API 연동)
  - [ ] 목록 출력
  - [ ] 상세조회
  - [ ] 수정
  - [ ] 리마인더 전송(?)
- [ ] 채용 공고화면에서 지원하기
