### ISSUE TITLE
TODO: 고기성

### ISSUE THREAD

**Issue by Gogisung** [SEONGNAM-SELLDOK/CLONE-PROJECT#46]
- [x] 기업등록에서 userinfo 가져오기(employee에 추가)
- [x] 탐색 링크 연결
- [ ] 구직정보 리스트에서 수정 페이지 구별(userName으로 구분하고 로그아웃하면 userName null 처리 Vuex)
- [x] 메인페이지 탐색 링크 연결하기
- [x] 신규 채용 회사 Main 구현
- [ ] 금주 추천 뷰카운트 기준 구현
