### ISSUE TITLE
TODO: 고기성

### ISSUE THREAD

**Issue by Gogisung** [SEONGNAM-SELLDOK/CLONE-PROJECT#53]
- [x] spring rest docs
- [x] swagger
- [x] 금주의 추천 api
   - [x] 엔티티 추가
   - [x] api 개발
- [x] 리스트 페이지 필요 없는 부분 삭제
- [ ] 타임리프 변경방인
