### ISSUE TITLE
TODO 김동석

### ISSUE THREAD

**Issue by bluedskim** [SEONGNAM-SELLDOK/CLONE-PROJECT#62]
### 새기능
- [ ] controlleradvice & exceptionhandler 추가

### 변경
- [ ] 지원자목록화면을 현재 로그인 사용자의 회사의 지원자 목록으로만 출력(~/company/applications)

### 개선
- [ ] Karate, Taurus 스크립트를 프로젝트 폴더 최상위에 폴더 하나 만들어서 넣기
